package com.hereliesaz.geministrator.memory

import com.hereliesaz.geministrator.resources.Res
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import no.synth.kmpzip.gzip.GzipInputStream
import no.synth.kmpzip.io.readBytes
import org.jetbrains.compose.resources.ExperimentalResourceApi

/**
 * The static language data the programmatic clerks read: WordNet 3.1 and the part-of-speech tagger
 * weights. Both are gzip'd text resources generated by tools/memory_lexicon; they load once, on the
 * first clerk that needs them, and stay in memory.
 */
internal class MemoryLanguageResources(
    val wordNet: WordNetLexicon,
    val tagger: PerceptronPosTagger,
) {
    companion object {
        const val WORDNET_FILE: String = "files/aive-wordnet-v1.txt.gz"
        const val TAGGER_FILE: String = "files/aive-pos-tagger-v1.txt.gz"

        private val mutex = Mutex()
        private var loaded: MemoryLanguageResources? = null

        /** Loads (once) and returns the shared resources. */
        suspend fun get(): MemoryLanguageResources = loaded ?: mutex.withLock {
            loaded ?: fromText(read(WORDNET_FILE), read(TAGGER_FILE)).also { loaded = it }
        }

        /** Already loaded resources, or null; for synchronous callers that can fall back. */
        fun loadedOrNull(): MemoryLanguageResources? = loaded

        fun fromText(wordNetText: String, taggerText: String): MemoryLanguageResources {
            val wordNet = WordNetLexicon.parse(wordNetText)
            return MemoryLanguageResources(wordNet, PerceptronPosTagger.parse(taggerText, wordNet))
        }

        @OptIn(ExperimentalResourceApi::class)
        private suspend fun read(path: String): String = gunzip(Res.readBytes(path))

        fun gunzip(bytes: ByteArray): String = GzipInputStream(bytes).readBytes().decodeToString()
    }
}
